spring:
  datasource:
    url: jdbc:postgresql://master_bd:5432/ip_geofinder
    username: ip_geofinder_user
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: ip_geofinder_schema
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
  application:
    name: ip-geofinder
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://eureka-server-host:8761/eureka/

